name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: fahad10inb
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: output/
      - name: Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin main
